### ISSUE TITLE
Dimension crash

### ISSUE THREAD

**Issue by HeberonYT** [TragicNeko/TragicMC2-1.8#1]
Hello!
I am using your mod on my public server, but I have several problems and conflicts that cause falls and reboots when visiting TagicMC dimensions, attached reports and records.
Crash: https://pastebin.com/raw/vw2MB5sS

The report also performs with developers Galacticraft but mentioned that the mod was not the cause reboots.

I also want to mention that TragicMC shows a lot of information on the console, it does whenever an enemy of any kind is hit. This causes logs over 60GB of content generated in a single day.
I hope you can solve these two problems,

TragicMC2-1.7.10-2.46.2876.jar

_Greetings!_

**Comment by TragicNeko** [comment]
I cannot recreate the crash that you have the report for but it seems like a very common crash for Dimensional mods. The logger spam was taken care of and a new version was released on the CurseForge website for the mod.

**Comment by HeberonYT** [comment]
Thanks for your quick response.
So is there no solution to this conflict dimensions? I've checked the ID but are not the problem.
It should be mentioned that the report says that the cause is a user called "Dandarus" which is in the DIM17 dimension, that dimension corresponds to the mod Atum, and ask the user if he has visited the dimensions of tragicmc and told me not .
It is very difficult to identify the real cause.

Regards!

**Comment by HeberonYT** [comment]
Hello
Update: This problem has been solved by assigning biome IDs to avoid conflict with other mods, for example galacticraft.
Thanks for the help yet.
